### ISSUE TITLE
I changed to use raspberry pi, but still got error, please guide.

### ISSUE THREAD

**Issue by TTTTyler** [KipCrossing/Micropython-AD9833#2]
Hi ,I used Raspberry Pi and set up spi and ss pins, and changed spi.send(to_send) to spi.xfer(to_send), still got error, wave.send()，An error occurred,Please guide.

My code

from ad9833 import AD9833
import spidev
import RPi.GPIO as GPIO

pin_id=7

def get_RPi_spi(mode = 0b10, lsbfirst = False):
   
    spi = spidev.SpiDev()
    spi.open(0, 0)
    spi.max_speed_hz = 9600
    spi.mode = mode
    spi.lsbfirst = lsbfirst
    return spi

GPIO.setmode(GPIO.BCM)
_ss = GPIO.setup(pin_id, GPIO.OUT)
_spi = get_RPi_spi

wave = AD9833(_spi,_ss)

wave.set_freq(14500)

wave.set_type(0)
wave.send()
print(wave.shape_type)
print(wave.freq)

Traceback (most recent call last): File "/home/a123456/Desktop/Micropython-AD9833-master/AD9833-TEST.py", line 31, in <module> 
           wave. send() 
File "/home/a123456/Desktop/Micropython-AD9833-master/ad9833.py", line 58, in send 
        self._send(0x2100)
File "/home/a123456/Desktop/Micropython-AD9833-master/ad9833.py", line 19, in send self,_send(Ox2100) 
         self . ss.low() 
AttributeError: 'NoneType' object has no attribute 'low"

**Comment by KipCrossing** [comment]
Closing as this is not an issue with the source code
